# Default configuration for BerryJar

gameplayTweaks:
   simplifySleep: true   # Whether or not sleeping should forward time to day when half of the online players are asleep
   melee-skeletons: true   # Whether we should spawn skeletons that use melee weapons instead of bows
   melee-skeletons-with-axes: false   # Whether or not those skeletons should ever have axes
   faster-zombies: false
   no-zombie-babies: true
   
sounds:
   chatMessages: true
   joinMessages: true
   leaveMessages: false
   kickMessages: false
   crafting: true
   crafting-in-inventory: false
   