gameplayTweaks:
   # Whether or not sleeping should forward time to day when half of the online players are asleep
   simplifySleep: true
   # Whether we should also spawn skeletons that use melee weapons
   melee-skeletons: true
   # Whether or not those skeletons should ever have axes
   melee-skeletons-with-axes: false
   # If some zombies should spawn with a speed potion effect
   faster-zombies: false
   # Disable baby zombies from spawning
   no-zombie-babies: true
   # Add a unique chat message for manually disconnected players
   unique-kick-message: true

sounds:
   chatMessages: true
   joinMessages: true
   leaveMessages: false
   kickMessages: false
   crafting: true
   crafting-in-inventory: false
