name: BerriesJar
version: 0.1.10-SNAPSHOT
description: Sweet and prickly tweaks for your modern Minecraft server
author: WolfNT90
main: io.github.wolfnt90.berriesjar.BerriesJarPlugin
api-version: 1.18
