name: BerryJar
version: 0.0.1
description: Sweet and prickly tweaks for your modern Minecraft server
author: WolfNT90
main: io.github.wolfnt90.berriesjar.Berry
api-version: 1.14
commands:
     berry:
        description: Main command for BerriesJar
     b:
        description: Alias for main command of Berries